### ISSUE TITLE
Is it possible to get it work with 3rd party components?

### ISSUE THREAD

**Issue by maicol07** [ArthurClemens/cyano#10]
Hi,
I've looked the README and cyano looks great! However, I'm not able to convert React components into Mithril components (for example [RMWC](https://rmwc.io)). Is this behaviour supported or only custom components written inside the library or application works?

**Comment by ArthurClemens** [comment]
Cyano provides a "shared code base" from where both Mithril and React components are built. An external library won't have this Cyano code base, so converting won't work this way.

RMWC is built on top of Google's Web Components. It is possible to use the same methodology for Mithril. Of you could just use the Web Components in a Mithril project.
